# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeAIapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeAIapp

  pod 'Firebase/Core'

  target 'RecipeAIappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecipeAIappUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
